config/routes.rb
# == Route Map
#
#   Prefix Verb   URI Pattern          Controller#Action
#    posts GET    /posts(.:format)     posts#index
#          POST   /posts(.:format)     posts#create
# new_post GET    /posts/new(.:format) posts#new
#     root GET    /                    posts#index
#   signin GET    /signin(.:format)    sessions#new
#          POST   /signin(.:format)    sessions#create
#  signout DELETE /signout(.:format)   sessions#destroy
#

Rails.application.routes.draw do

	resources :posts, only: [:new, :create, :index]
	root 'posts#index'

	get     'signin'   =>  'sessions#new'
	post    'signin'   =>  'sessions#create'
	delete  'signout'  =>  'sessions#destroy'
  
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#

class Post < ActiveRecord::Base

	belongs_to :user
	
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  remember_token  :string
#

class User < ActiveRecord::Base

	has_many :posts
	# Downcase the email and name attributes before saving the user
	before_save { self.email = email.downcase }
	before_save { self.name  = name.downcase }

	# Before the create action is run we need to create a remember token
	before_create :create_remember_token

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }

	# Returns a random token when called from create_remember_token
	# See listing 8.31 of the rails tutorial for generating tokens.
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	# Returns the hash digest of the given string
	# See listing 8.32: Adding a remember method to the User model
	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		# Calls new_remember_token which is then passed to User.digest
		# which encrypts the token, and using self ensures that by assignment 
		# we set the user’s remember_token attribute in the database
		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :signed_in_user, only: [:new, :create]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		@post.save
		redirect_to root_path
	end

	private

		def post_params
			params.require(:post).permit(:title, :body)  
		end
		
		# before filter
		def signed_in_user
			unless signed_in?
				redirect_to signin_url
			end
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
    	if user && user.authenticate(params[:session][:password])
      		sign_in user
      		redirect_to root_path
	    else
			flash.now[:danger] = 'Invalid email/password combination'
			render 'new'
	    end
	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


	# The sign_in method creates a new token and sets cookie equal to new token, 
	# the user's token is then updated with hashed token.
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	# Retrieve the current user with the ||= operator
	# if the current user is already set, you should return that user, 
	# or you'll need to pull out the remember token from the cookie and 
	# search for it in your database to pull up the corresponding user
	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	# Set the current user
	def current_user=(user)
		@current_user = user
	end

	# 
	def signed_in?
		!current_user.nil?
	end

	# Sign the user out
	def sign_out
		current_user.update_attribute( :remember_token,
									   User.digest(User.new_remember_token ))
		cookies.delete(:remember_token)
		self.current_user = nil
	end
	
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BRAND", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="app-navbar-collapse">
      <ul class="nav navbar-nav">
        <% if signed_in? %>
          <li class="<%= 'active' if current_page?(new_post_path) %>">
            <%= link_to "New Post", new_post_path %>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li>
            <%= link_to "(#{current_user.name}) Sign out", signout_path, method: "delete" %>
          </li>
        <% else %>
          <li class="<%= 'active' if current_page?(signin_path) %>">
            <%= link_to 'Sign in', signin_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/nav' %>

<div class="container">

	<%= yield %>

	<%= debug(params) if Rails.env.development? %>	
	
</div>


</body>
</html>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<% @posts.each do |post| %>
			<div class="well">
				<h4><%=post.title %></h4>
				<p><%= post.body %></p>
				<% if signed_in? %>
					<p>Posted by: <%= post.user.name %></p>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>

	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body, class: 'form-control' %>
	</div>

  <%= f.submit "Post", class: "btn btn-primary"%>


<% end %>